/**
 * `inon_id` — a workspace-wide, locally-minted UUID stamped onto every
 * `.md` document the CLI touches.
 *
 * Invariant: every `.md` in the workspace that the CLI has written or
 * mutated carries an `inon_id` field in its YAML frontmatter. The id is
 * generated by the CLI (it is NOT a cloud-side identifier like
 * `notion_id` / `lark_id`) and is preserved across updates so it
 * functions as a stable, platform-agnostic identity.
 */
import { randomUUID } from "crypto";

/**
 * Mint a fresh `inon_id`. Backed by `crypto.randomUUID()` (Node 18+),
 * which produces a v4 UUID per WHATWG. Collision probability is
 * negligible for any single workspace.
 */
export function mintInonId(): string {
  return randomUUID();
}

/**
 * Idempotent: set `inon_id` on `fm` if it is missing or empty. Returns
 * the same object reference (mutated in place) so callers can chain or
 * pass through.
 *
 * Rules:
 *   - `fm.inon_id` is a non-empty string → leave alone (preserve).
 *   - `fm.inon_id` is missing, null, undefined, or "" → mint + set.
 *   - Otherwise (e.g. number, boolean, object) → treat as invalid,
 *     overwrite with a fresh mint. We refuse to trust non-strings so a
 *     hand-typed junk value cannot shadow a real id.
 *
 * Returning the same reference is intentional: the codebase's
 * `writeFrontmatterBody` already mutates-and-uses the same frontmatter
 * object, and `shot/replace.ts` does the same.
 */
export function ensureInonId(fm: Record<string, unknown>): Record<string, unknown> {
  const cur = fm.inon_id;
  if (typeof cur === "string" && cur.length > 0) return fm;
  fm.inon_id = mintInonId();
  return fm;
}